name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - "1.70"
          - stable
          - nightly
        cargo-update:
          - true
        include:
          - rust: stable
            cargo-update: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Update
        if: matrix.cargo-update
        run: cargo update
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt clippy
      - name: Run rustfmt check
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all --all-targets -- -D warnings

